### ISSUE TITLE
[Suggestion] Start a 'testing' branch?

### ISSUE THREAD

**Issue by collectorgeneral** [y20k/trackbook#11] opened 2017-01-21 14:53 UTC
I noticed we were having a lot of back and forth conversations and you upload a lot of apk. I was thinking if it would be a better idea to have a separate branch (probably called 'unstable'/'test' or something along) and post releases there? This might save you time to manually link unstable/test apks and have everything in one place where I can just go to /releases and download the apk.  When you are certain that things are more or less stable, you can move the sources to the master branch and release the final version there.

**Comment by y20k** [comment] 2017-01-23 10:06
I thought about starting a testing branch before. I have no experience with working on two branches. Frankly I am a bit afraid of what consequences that would have. For example. How well does the automated code merging would work. How do I handle the internal versioning.

In my opinion two branches start to make sense in a scenario, where at the same time I would need to fix bugs and develop a huge new feature. In that case I could only pursue one thing (bug OR new feature). My only other experience with open source coding so far is Transistor. In this project I only once had this problem. 

My guess is that as soon as more people work on the app at the same time, a testing branch becomes a must. For now I hesitate to try that out. The situation with some of the bugs you encountered where a bit special, because I had to hand out betas so that you can test them. I hope future bugs will be of the nature, that I can reproduce them better and so can test the solutions myself.

**Comment by collectorgeneral** [comment] 2017-01-23 11:09
@y20k Sure, it was just something I thought would be a good idea. You can also just create it to dumb test apk's. Again, if you are not particularly comfortable with, I do not really mind 😄 .

**Comment by y20k** [comment] 2017-03-13 21:15
I am closing the issue for now. I will keep it in mind though. Maybe there is a stronger need to implement a testing branch in the future.

**Closed by y20k** 2017-03-13 21:15 UTC
Labels: enhancement
