### ISSUE TITLE
[Minor Bug] Erroneous total duration

### ISSUE THREAD

**Issue by collectorgeneral** [y20k/trackbook#5] opened 2016-12-21 13:46 UTC
After recording, in the 'Last Track' tab and under the statistics, the total duration is always 00:00:00. The start and end time are the same, appears to be the end time.

**Comment by y20k** [comment] 2016-12-21 14:08
That happens on my device only if you are recording a very short track (< 15 seconds).

**Comment by y20k** [comment] 2016-12-21 21:17
Oh. That is interesting. Can you do me a favour and open the last track file in a text editor and see, if it the dates has been saved wrongly?

And thanks again for the great help in testing the app!!

**Comment by y20k** [comment] 2016-12-21 21:17
Oh. That is interesting. Can you do me a favour and open the last track file in a text editor and see, if it the dates has been saved wrongly?

And thanks again for the great help in testing the app!!

**Comment by collectorgeneral** [comment] 2016-12-21 21:29
Oh shush ;3 it oke :d It is criminal to not support a dev who is working hard to develop it :3

Interestingly, that is what it seems to be doing. I opened the file, and I can see that this info is stored at the very end. Here is what I found for that screenshot:

... ,"c":3035.293,"d":0,"e":4198.0,"f":"Dec 20, 2016 21:06:11","g":"Dec 20, 2016 21:06:11"}

So obviously I assume c = total distance in KM, e = number of steps taken, f,g = start and end date, and by subtracting these, you get d, which is the duration. 

So there, I can clearly see that f = g, so subtracting them will give you zero.

**Comment by y20k** [comment] 2016-12-22 14:04
Thanks. I will look into it. It looks like the function that stores the end of a track never gets called. This bug is strange since I cannot reproduce it on my device. Anything special with your test device? Custom ROM? Low RAM? Which Android Version (maybe I can use an emulator to test)?

**Comment by collectorgeneral** [comment] 2016-12-22 17:57
Oh my god, I forgot to tell you that. Sorry! Please use this info for my other reports too:

General Information:
**App details:**
Version: 1 Beta ; Source: #2 
**Device Details:**
Device: Oneplus One (aka A0001 aka Bacon)
OS: Cyanogen OS 13.1.2, Build: ZNH2KAS3P0 (Android 6.0.1)

**Comment by y20k** [comment] 2017-01-09 17:10
I have an idea of what might have caused the error: 

If the app is in the background, the visible part is being paused. The UI does not update during that time. If you press stop in the notification the background service is paused/stopped. If you then tap on the notification again to bring up the UI, the app tries to recreate its state. In some cases the app can only recreate an "older" state, where the track end time has not been set (- because there was no way to update the UI while paused).

My solution: The app now creates a temp track-file as soon as you press "stop". And when you try to bring up the UI the app is now looking for this file.

I am going to test this later today. If you are interested and if you have time, please test it on your device, too. Here is a new test APK: [trackbook-app-test-1.0.0b.apk](https://www.dropbox.com/s/9t1bfil0w8wa3t9/trackbook-app-test-1.0.0b.apk?dl=0) (based on: [commit 36e91bf](https://github.com/y20k/trackbook/commit/702a2ecd054ee8f69fc8f080977ced15970fc72c))

**Comment by y20k** [comment] 2017-01-09 18:41
I tested the current beta version posted today. Result: The last track tab does not always show the correct track. It is actually worse than before :-) I am going to fix that in the next couple of days. You should probably wait for an update.

**Comment by collectorgeneral** [comment] 2017-01-09 21:38
Hm interesting. Alright, I will definitely try out the new update when you release it!

**Comment by y20k** [comment] 2017-01-11 21:05
Okay. After some tweaks and fixes, I think I got this bug fixed. If I really solved it, the problem itself was easy to fix. But during testing this fix I found a handful of other nasty bugs that really needed to be addressed. Anyway here is a new signed APK for testing. It would be great I you could have a look on it: 

[trackbook-app-test-1.0.0c.apk](https://www.dropbox.com/s/zu0hw1ap28w0zd2/trackbook-app-test-1.0.0c.apk?dl=0) (based on: commit [6ddcf3a](https://github.com/y20k/trackbook/commit/6ddcf3ae67ef49cb3bb04396117c64d5688ac1f5))

**Comment by collectorgeneral** [comment] 2017-01-13 19:02
See #7 .

**Comment by y20k** [comment] 2017-01-20 09:00
The bug seems to be fixed. I will close this issue. Feel free to reopen, if there is a case where it still comes up.

**Closed by y20k** 2017-01-20 09:00 UTC
Labels: bug
