### ISSUE TITLE
Version 1.1.5 does not start at all on Huawei P8 lite

### ISSUE THREAD

**Issue by LastZolex** [y20k/trackbook#34] opened 2018-03-20 12:41 UTC
Hi there,

I am a user of the app for a while and I am absolutely thrilled about it, because it is exactly the app I was looking for (for ages) ;-)

Since the update to 1.1.5 it does not work for me anymore. After going back to 1.0.8 it works again, so I guess there is a problem form me with the new 1.1.x stream of the app.

My Environment: 
* Huawei P8 lite (ALE-L21) with Android 6.0, EMUI 4.03

Probem Description:
* Starting the app makes the screen flickr for the fraction of a second, and then I am back to the launcher again
* This can be repeated (probably) indefinitely

There is no error message or any other means to get more information on this bug, I am sorry :(

Does anybody else have such a problem with the recent version?

Cheers

LZ

**Comment by y20k** [comment] 2018-03-20 12:56
Thanks for reporting this.  Lets see.

Version 1.1.4 introduced a new file format that can store altitude data. To see if this is the bug, please try to install version 1.1.3. If 1.1.3 does not crash the problem is likely caused by the new
format. 

Also with the current version 1.1.5 you could try to temporarily remove all the files from `/Android/data/org.y20k.trackbook/files/tracks.` and see if that changes anything.

**Comment by LastZolex** [comment] 2018-03-20 13:41
good idea. I guess I can find the version 1,1,3 best on F-Droid? 
I wish the google play store had a feature to choose the right versions!! ;-)

A soon as I have tried both approaches I will report the results:

**Comment by y20k** [comment] 2018-03-20 13:43
The easiest way is to head over to https://github.com/y20k/trackbook/releases

**Comment by LastZolex** [comment] 2018-03-20 13:57
That's a good hint, and so obvious! ;-)

Ok, I checked it:

* Installing 1.1.3 from F-Droid: working fine
* Afterwards updateing to 1.1.5 : Crashing as usual
** I did not find any file in nor the directory you described itself... maybe this is part of the problem?
** I searched it in the internal SD Android-directories and in the external SD Android-directory

Your idea with the new file data seems to be valid.

I hope this info helps you ;-)

**Comment by y20k** [comment] 2018-03-20 15:02
Okay. Thanks. I got a similar problem description via email that points into another direction. It looks as if there is a problem with setting the background color for some of the interface elements.

I think I can fix that pretty easy. But since I cannot reproduce the issue, I cannot confirm, if it works. That is why I am sharing a pre-release version of Trackbook here:

* [trackbook-app-test-1.1.6-01.apk](https://www.dropbox.com/s/8nrj18s7r65ltns/trackbook-app-test-1.1.6-01.apk?dl=0) (based on this code base [5b08913](https://github.com/y20k/trackbook/tree/5b089130fda32bf9d2f64613e75d21f4cd8f961b))

There is not much new in this version - and it is save to use. The only change compared to v1.1.5 is that this version will feature a Resume option (see #33). This feature is not working properly yet. I would advice not to use it. But apart from that everything should work as expected.

**Comment by LastZolex** [comment] 2018-03-20 15:30
Thanks for the quick reply. I installed the version and it still crashes like before :(

The screen flashes shortly to white, which probably is the app background of the welcome-page,
and then I am back to the launcher screen.

**Comment by y20k** [comment] 2018-03-20 15:32
Just curious. Do you have location turned on?

**Comment by LastZolex** [comment] 2018-03-20 15:33
I had the same idea and turned it on and tried it again... unfortunately I sit in a dark developer dungeon where I have no GPS signal :-/

But I will try this again later outside and send you a notice :D

**Comment by y20k** [comment] 2018-03-20 15:38
Okay. I am tapping a bit in the dark, too. Can you try to delete the app data and restart the app.

![2018-03-20-16 36 40](https://user-images.githubusercontent.com/9103935/37665259-23e7f7fc-2c5d-11e8-8c59-b65d0b758d84.png)
![2018-03-20-16 36 51](https://user-images.githubusercontent.com/9103935/37665260-240bd672-2c5d-11e8-9ff4-0cb097aab169.png)

**Comment by y20k** [comment] 2018-03-20 16:02
I am really sorry to keep you busy. But since on my device everything works fine, I need your feedback. I have another idea. v1.1.5 introduces what I call the "secret night mode switch".

To find out if this switch is the culprit. Please try out v1.1.4.
https://github.com/y20k/trackbook/releases

if v1.1.4 works, but v1.1.5 does not that may mean: file format (introduced in v1.1.4) is not the issue, but probably the night mode switch.

**Comment by y20k** [comment] 2018-03-20 19:28
Hi @LastZolex 
Thanks to your help and thanks to the help of two other guys who contacted me via email I think I found the issue. A new version of Trackbook that should not crash at startup is out. See [v1.1.6](https://github.com/y20k/trackbook/releases/tag/v1.1.6) and [Google Play](https://play.google.com/store/apps/details?id=org.y20k.trackbook). I will close this issue here. Please reopen, if the problems persists.

**Closed by y20k** 2018-03-20 19:28 UTC

**Comment by LastZolex** [comment] 2018-03-21 13:47
You are a genius! Thank you so much for the quick help!
I wish I could have helped you more ;-)

My installed version 1.1.6 works fine - as usual! ;-)

Thank you!!
